/**
 * One file to paste into the Supabase SQL editor on a new project: every
 * migration in order, then the seed. Written by `npm run build:setup-sql` to
 * supabase/setup-all.sql; setupSql.test.ts keeps that file in step.
 */
import { readdirSync, readFileSync } from 'node:fs';

const root = new URL('../supabase/', import.meta.url);

export function setupSql(): string {
  const migrations = readdirSync(new URL('migrations/', root))
    .filter((f) => /^\d{4}_.+\.sql$/.test(f))
    .sort();
  const parts = [
    ...migrations.map((f) => ({ name: `migrations/${f}`, sql: readFileSync(new URL(`migrations/${f}`, root), 'utf8') })),
    { name: 'seed.sql', sql: readFileSync(new URL('seed.sql', root), 'utf8') },
  ];
  const header = [
    '-- Grateful: complete database setup for a NEW Supabase project.',
    '-- Generated by `npm run build:setup-sql`. Do not edit: change the migrations or seed instead.',
    '-- Supabase → SQL Editor → New query → paste this whole file → Run. Run it once only.',
    `-- Contains, in order: ${parts.map((p) => p.name).join(', ')}.`,
  ].join('\n');
  return `${header}\n${parts.map((p) => `\n-- ===== ${p.name} =====\n\n${p.sql.trimEnd()}\n`).join('')}`;
}
