/**
 * Every food image on the site is a supplied bb.q master. No stock photography,
 * no placeholder blocks.
 *
 * Derivatives are pre-generated by infra/scripts/generate-image-derivatives.mjs
 * at 480 / 768 / 1200 wide in WebP with a JPEG fallback, so this renders a plain
 * <picture> and needs no image optimiser at runtime.
 */

type Crop = 'portrait' | 'wide';

const WIDTHS = [480, 768, 1200] as const;

export function FoodImage({
  imageKey,
  alt,
  crop = 'portrait',
  sizes,
  priority = false,
  className,
}: {
  imageKey: string;
  alt: string;
  crop?: Crop;
  /** Passed straight to srcset so the browser picks the right derivative. */
  sizes: string;
  priority?: boolean;
  className?: string;
}) {
  const suffix = crop === 'wide' ? '-wide' : '';
  const srcset = (extension: string) =>
    WIDTHS.map((width) => `/food/${imageKey}${suffix}-${width}.${extension} ${width}w`).join(', ');

  return (
    <picture>
      <source type="image/webp" srcSet={srcset('webp')} sizes={sizes} />
      <img
        src={`/food/${imageKey}${suffix}-768.jpg`}
        srcSet={srcset('jpg')}
        sizes={sizes}
        alt={alt}
        // Intrinsic ratio is declared so the layout does not shift as images
        // arrive, which is what the crop ratios were chosen to guarantee.
        width={crop === 'wide' ? 1600 : 960}
        height={crop === 'wide' ? 900 : 1200}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : 'auto'}
        decoding="async"
        className={className}
      />
    </picture>
  );
}
