#!/usr/bin/env node
/**
 * NMU ONE — photography derivative pipeline (brief §18, §30 "images are optimised").
 *
 * Reads every master in assets/photos/masters/ and writes three WebP widths
 * next to it, then regenerates src/content/photoFiles.generated.ts so the app
 * can only ever reference a photograph that exists.
 *
 *   sm   480w   thumbnails, small discovery cards
 *   md   960w   cards, phone heroes at @2x
 *   lg  1440w   phone heroes at @3x, the web build
 *
 * Every master is a 16:9 frame, so derivatives keep that ratio and screens
 * crop at render time with `contentPosition` (the focal point lives in
 * src/content/photos.ts). One set of files then serves every placement, and
 * the design team can replace a master without touching a component.
 *
 * Requires ImageMagick (`convert`). Run: npm run assets:photos
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const mastersDir = path.join(root, 'assets', 'photos', 'masters');

const SIZES = [
  ['sm', 480, 78],
  ['md', 960, 80],
  ['lg', 1440, 80],
];

const masters = readdirSync(mastersDir)
  .filter((f) => /\.(jpe?g|png)$/i.test(f))
  .sort();

if (masters.length === 0) {
  console.error('No masters found in', mastersDir);
  process.exit(1);
}

for (const [size, width, quality] of SIZES) {
  const outDir = path.join(root, 'assets', 'photos', size);
  mkdirSync(outDir, { recursive: true });
  for (const file of masters) {
    const stem = file.replace(/\.[^.]+$/, '');
    execFileSync('convert', [
      path.join(mastersDir, file),
      '-strip',
      '-resize',
      `${width}x>`,
      '-quality',
      String(quality),
      '-define',
      'webp:method=6',
      path.join(outDir, `${stem}.webp`),
    ]);
  }
}

const stems = masters.map((f) => f.replace(/\.[^.]+$/, ''));
const lines = stems.map((stem) => {
  const entries = SIZES.map(
    ([size]) => `    ${size}: require('../../assets/photos/${size}/${stem}.webp'),`,
  ).join('\n');
  return `  '${stem}': {\n${entries}\n  },`;
});

const out = `/* eslint-disable */
// GENERATED by scripts/derive-photos.mjs — do not edit by hand.
// Run \`npm run assets:photos\` after adding or replacing a master.

export const photoFiles = {
${lines.join('\n')}
} as const;

export type PhotoFileKey = keyof typeof photoFiles;
`;

writeFileSync(path.join(root, 'src', 'content', 'photoFiles.generated.ts'), out);
console.log(`Derived ${stems.length} photographs × ${SIZES.length} sizes.`);
