/* eslint-disable */
// GENERATED by scripts/derive-photos.mjs — do not edit by hand.
// Run `npm run assets:photos` after adding or replacing a master.

export const photoFiles = {
  'academic-success': {
    sm: require('../../assets/photos/sm/academic-success.webp'),
    md: require('../../assets/photos/md/academic-success.webp'),
    lg: require('../../assets/photos/lg/academic-success.webp'),
  },
  'alumni-giving': {
    sm: require('../../assets/photos/sm/alumni-giving.webp'),
    md: require('../../assets/photos/md/alumni-giving.webp'),
    lg: require('../../assets/photos/lg/alumni-giving.webp'),
  },
  'cafeteria': {
    sm: require('../../assets/photos/sm/cafeteria.webp'),
    md: require('../../assets/photos/md/cafeteria.webp'),
    lg: require('../../assets/photos/lg/cafeteria.webp'),
  },
  'campus-innovation': {
    sm: require('../../assets/photos/sm/campus-innovation.webp'),
    md: require('../../assets/photos/md/campus-innovation.webp'),
    lg: require('../../assets/photos/lg/campus-innovation.webp'),
  },
  'digital-learning': {
    sm: require('../../assets/photos/sm/digital-learning.webp'),
    md: require('../../assets/photos/md/digital-learning.webp'),
    lg: require('../../assets/photos/lg/digital-learning.webp'),
  },
  'events': {
    sm: require('../../assets/photos/sm/events.webp'),
    md: require('../../assets/photos/md/events.webp'),
    lg: require('../../assets/photos/lg/events.webp'),
  },
  'graduation': {
    sm: require('../../assets/photos/sm/graduation.webp'),
    md: require('../../assets/photos/md/graduation.webp'),
    lg: require('../../assets/photos/lg/graduation.webp'),
  },
  'hero-campus': {
    sm: require('../../assets/photos/sm/hero-campus.webp'),
    md: require('../../assets/photos/md/hero-campus.webp'),
    lg: require('../../assets/photos/lg/hero-campus.webp'),
  },
  'library': {
    sm: require('../../assets/photos/sm/library.webp'),
    md: require('../../assets/photos/md/library.webp'),
    lg: require('../../assets/photos/lg/library.webp'),
  },
  'nmu-community': {
    sm: require('../../assets/photos/sm/nmu-community.webp'),
    md: require('../../assets/photos/md/nmu-community.webp'),
    lg: require('../../assets/photos/lg/nmu-community.webp'),
  },
  'parent-connection': {
    sm: require('../../assets/photos/sm/parent-connection.webp'),
    md: require('../../assets/photos/md/parent-connection.webp'),
    lg: require('../../assets/photos/lg/parent-connection.webp'),
  },
  'residence': {
    sm: require('../../assets/photos/sm/residence.webp'),
    md: require('../../assets/photos/md/residence.webp'),
    lg: require('../../assets/photos/lg/residence.webp'),
  },
  'safety': {
    sm: require('../../assets/photos/sm/safety.webp'),
    md: require('../../assets/photos/md/safety.webp'),
    lg: require('../../assets/photos/lg/safety.webp'),
  },
  'shuttle': {
    sm: require('../../assets/photos/sm/shuttle.webp'),
    md: require('../../assets/photos/md/shuttle.webp'),
    lg: require('../../assets/photos/lg/shuttle.webp'),
  },
  'staff-lecturer': {
    sm: require('../../assets/photos/sm/staff-lecturer.webp'),
    md: require('../../assets/photos/md/staff-lecturer.webp'),
    lg: require('../../assets/photos/lg/staff-lecturer.webp'),
  },
  'student-journey': {
    sm: require('../../assets/photos/sm/student-journey.webp'),
    md: require('../../assets/photos/md/student-journey.webp'),
    lg: require('../../assets/photos/lg/student-journey.webp'),
  },
  'wellbeing': {
    sm: require('../../assets/photos/sm/wellbeing.webp'),
    md: require('../../assets/photos/md/wellbeing.webp'),
    lg: require('../../assets/photos/lg/wellbeing.webp'),
  },
} as const;

export type PhotoFileKey = keyof typeof photoFiles;
