import type { Href } from 'expo-router';
import type { IconName } from '@/design';
import type { World } from '@/core/domain/models';
import type { Capability } from '@/core/permissions/policy';

/**
 * The service directory: everything NMU ONE can do, grouped into the five
 * product worlds (brief §4) rather than by department, and filtered by the
 * same capabilities that guard the routes.
 */
export interface ServiceEntry {
  id: string;
  title: string;
  summary: string;
  world: World;
  href: Href;
  icon: IconName;
  capability: Capability;
  keywords: string[];
}

export const WORLDS: { id: World; title: string; summary: string }[] = [
  { id: 'academics', title: 'Academics', summary: 'Classes, assessments and results' },
  { id: 'campus', title: 'Campus', summary: 'Getting around and getting things done' },
  { id: 'money', title: 'Money', summary: 'Fees, funding and payments' },
  { id: 'community', title: 'Community', summary: 'Events, societies, safety and wellbeing' },
  { id: 'alumni', title: 'Alumni', summary: 'Mentoring, careers and giving' },
];

export const SERVICES: ServiceEntry[] = [
  {
    id: 'timetable',
    title: 'Timetable',
    summary: 'Today and the week ahead',
    world: 'academics',
    href: '/academics/timetable',
    icon: 'calendar-outline',
    capability: 'academics.timetable',
    keywords: ['class', 'lecture', 'schedule', 'venue'],
  },
  {
    id: 'teaching',
    title: 'Teaching schedule',
    summary: 'Your lectures and consultations',
    world: 'academics',
    href: '/academics/teaching',
    icon: 'easel-outline',
    capability: 'teaching.schedule',
    keywords: ['lecture', 'teach', 'schedule'],
  },
  {
    id: 'exams',
    title: 'Exams & assessments',
    summary: 'Dates, venues and countdowns',
    world: 'academics',
    href: '/academics/exams',
    icon: 'alarm-outline',
    capability: 'academics.exams',
    keywords: ['exam', 'test', 'assignment', 'deadline'],
  },
  {
    id: 'results',
    title: 'Results & progress',
    summary: 'Marks and credits',
    world: 'academics',
    href: '/academics/results',
    icon: 'ribbon-outline',
    capability: 'academics.results',
    keywords: ['marks', 'grades', 'credits'],
  },
  {
    id: 'modules',
    title: 'Modules & LMS',
    summary: 'Your modules and course pages',
    world: 'academics',
    href: '/academics/modules',
    icon: 'library-outline',
    capability: 'academics.modules',
    keywords: ['moodle', 'lms', 'course'],
  },
  {
    id: 'calendar',
    title: 'Academic calendar',
    summary: 'Term dates and ceremonies',
    world: 'academics',
    href: '/academics/calendar',
    icon: 'today-outline',
    capability: 'academics.calendar',
    keywords: ['term', 'dates', 'holiday', 'graduation'],
  },

  {
    id: 'map',
    title: 'Campus map',
    summary: 'Buildings, rooms and directions',
    world: 'campus',
    href: '/campus-map',
    icon: 'map-outline',
    capability: 'campus.map',
    keywords: ['where', 'building', 'room', 'directions', 'navigate'],
  },
  {
    id: 'shuttle',
    title: 'Shuttle',
    summary: 'Live arrivals and routes',
    world: 'campus',
    href: '/transport',
    icon: 'bus-outline',
    capability: 'transport.view',
    keywords: ['bus', 'transport', 'ride'],
  },
  {
    id: 'library',
    title: 'Library',
    summary: 'Search and book study spaces',
    world: 'campus',
    href: '/library',
    icon: 'book-outline',
    capability: 'library.search',
    keywords: ['books', 'study', 'room', 'space'],
  },
  {
    id: 'dining',
    title: 'Food & campus shops',
    summary: 'Order ahead and collect',
    world: 'campus',
    href: '/dining',
    icon: 'restaurant-outline',
    capability: 'dining.view',
    keywords: ['food', 'lunch', 'coffee', 'order', 'eat'],
  },
  {
    id: 'residence',
    title: 'Residence',
    summary: 'Your room and requests',
    world: 'campus',
    href: '/residence',
    icon: 'home-outline',
    capability: 'residence.view',
    keywords: ['res', 'room', 'maintenance', 'warden'],
  },
  {
    id: 'directory',
    title: 'Staff directory',
    summary: 'Find a lecturer or office',
    world: 'campus',
    href: '/directory',
    icon: 'people-outline',
    capability: 'directory.view',
    keywords: ['lecturer', 'staff', 'office', 'consultation'],
  },

  {
    id: 'fees',
    title: 'Fees & statement',
    summary: 'Balance, statement and receipts',
    world: 'money',
    href: '/money',
    icon: 'wallet-outline',
    capability: 'finance.view',
    keywords: ['owe', 'balance', 'statement', 'pay'],
  },
  {
    id: 'funding',
    title: 'Funding status',
    summary: 'NSFAS and bursaries',
    world: 'money',
    href: '/money/funding',
    icon: 'cash-outline',
    capability: 'funding.view',
    keywords: ['nsfas', 'bursary', 'allowance'],
  },
  {
    id: 'shared-fees',
    title: 'Shared fees',
    summary: 'The fee position your student shares',
    world: 'money',
    href: '/guardian/fees',
    icon: 'wallet-outline',
    capability: 'guardian.fees',
    keywords: ['owe', 'balance', 'fees'],
  },
  {
    id: 'pay',
    title: 'Make a payment',
    summary: 'Approved payment providers only',
    world: 'money',
    href: '/money/pay',
    icon: 'card-outline',
    capability: 'finance.pay',
    keywords: ['pay', 'eft', 'card'],
  },

  {
    id: 'events',
    title: 'Events',
    summary: 'What’s on, tickets and reminders',
    world: 'community',
    href: '/events',
    icon: 'sparkles-outline',
    capability: 'events.view',
    keywords: ['event', 'concert', 'festival', 'ticket'],
  },
  {
    id: 'societies',
    title: 'Societies',
    summary: 'Find your people',
    world: 'community',
    href: '/societies',
    icon: 'people-circle-outline',
    capability: 'events.view',
    keywords: ['club', 'society', 'join'],
  },
  {
    id: 'safety',
    title: 'Safety',
    summary: 'Emergency help and safe travel',
    world: 'community',
    href: '/safety',
    icon: 'shield-checkmark-outline',
    capability: 'safety.view',
    keywords: ['emergency', 'security', 'protection', 'unsafe'],
  },
  {
    id: 'wellbeing',
    title: 'Wellbeing',
    summary: 'Counselling and support',
    world: 'community',
    href: '/wellbeing',
    icon: 'heart-outline',
    capability: 'wellbeing.view',
    keywords: ['counselling', 'stress', 'health', 'food support'],
  },
  {
    id: 'family',
    title: 'Your student',
    summary: 'What your student has shared',
    world: 'community',
    href: '/guardian',
    icon: 'people-outline',
    capability: 'guardian.linked-student',
    keywords: ['family', 'parent', 'guardian'],
  },

  {
    id: 'alumni',
    title: 'Alumni home',
    summary: 'Your profile and community',
    world: 'alumni',
    href: '/alumni',
    icon: 'school-outline',
    capability: 'alumni.profile',
    keywords: ['alumni', 'chapter', 'profile'],
  },
  {
    id: 'mentoring',
    title: 'Mentoring',
    summary: 'Give back an hour a month',
    world: 'alumni',
    href: '/alumni/mentoring',
    icon: 'chatbubbles-outline',
    capability: 'alumni.mentoring',
    keywords: ['mentor', 'mentee'],
  },
  {
    id: 'jobs',
    title: 'Careers & jobs',
    summary: 'Roles shared by alumni',
    world: 'alumni',
    href: '/alumni/jobs',
    icon: 'briefcase-outline',
    capability: 'alumni.jobs',
    keywords: ['job', 'career', 'work', 'vacancy'],
  },
  {
    id: 'giving',
    title: 'Giving',
    summary: 'Bursaries and student support',
    world: 'alumni',
    href: '/alumni/giving',
    icon: 'gift-outline',
    capability: 'alumni.giving',
    keywords: ['donate', 'give', 'bursary'],
  },
];
