// GENERATED by scripts/derive-photos.mjs — do not edit. Run `npm run assets:photos`.

export interface PhotoEntry {
  source: number;
  width: number;
  height: number;
  /** 'brand-board' crops are low resolution: cards and thumbnails only. */
  origin: 'photograph' | 'brand-board';
}

export const photoRegistry = {
  'bar-lounge': {
    source: require('../../assets/photos/bar-lounge.jpg'),
    width: 368,
    height: 457,
    origin: 'brand-board',
  },
  chandeliers: {
    source: require('../../assets/photos/chandeliers.jpg'),
    width: 509,
    height: 288,
    origin: 'brand-board',
  },
  'dining-room': {
    source: require('../../assets/photos/dining-room.jpg'),
    width: 1122,
    height: 1402,
    origin: 'photograph',
  },
  'dish-cocktails': {
    source: require('../../assets/photos/dish-cocktails.jpg'),
    width: 163,
    height: 205,
    origin: 'brand-board',
  },
  'dish-desserts': {
    source: require('../../assets/photos/dish-desserts.jpg'),
    width: 218,
    height: 205,
    origin: 'brand-board',
  },
  'dish-private-functions': {
    source: require('../../assets/photos/dish-private-functions.jpg'),
    width: 214,
    height: 205,
    origin: 'brand-board',
  },
  'dish-seafood': {
    source: require('../../assets/photos/dish-seafood.jpg'),
    width: 226,
    height: 205,
    origin: 'brand-board',
  },
  'dish-signature-mains': {
    source: require('../../assets/photos/dish-signature-mains.jpg'),
    width: 219,
    height: 205,
    origin: 'brand-board',
  },
  'dish-wines': {
    source: require('../../assets/photos/dish-wines.jpg'),
    width: 198,
    height: 205,
    origin: 'brand-board',
  },
  'fillet-closeup': {
    source: require('../../assets/photos/fillet-closeup.jpg'),
    width: 1122,
    height: 1402,
    origin: 'photograph',
  },
  'floor-pattern': {
    source: require('../../assets/photos/floor-pattern.jpg'),
    width: 366,
    height: 288,
    origin: 'brand-board',
  },
  'private-dining': {
    source: require('../../assets/photos/private-dining.jpg'),
    width: 1122,
    height: 1402,
    origin: 'photograph',
  },
  'private-welcome': {
    source: require('../../assets/photos/private-welcome.jpg'),
    width: 1536,
    height: 1024,
    origin: 'photograph',
  },
  'seafood-pan': {
    source: require('../../assets/photos/seafood-pan.jpg'),
    width: 1312,
    height: 1199,
    origin: 'photograph',
  },
  'signature-steak': {
    source: require('../../assets/photos/signature-steak.jpg'),
    width: 1122,
    height: 1402,
    origin: 'photograph',
  },
  'table-setting': {
    source: require('../../assets/photos/table-setting.jpg'),
    width: 285,
    height: 424,
    origin: 'brand-board',
  },
  'texture-marble': {
    source: require('../../assets/photos/texture-marble.jpg'),
    width: 150,
    height: 63,
    origin: 'brand-board',
  },
  'texture-pattern': {
    source: require('../../assets/photos/texture-pattern.jpg'),
    width: 150,
    height: 104,
    origin: 'brand-board',
  },
  'texture-timber': {
    source: require('../../assets/photos/texture-timber.jpg'),
    width: 150,
    height: 95,
    origin: 'brand-board',
  },
  'wagyu-sliced': {
    source: require('../../assets/photos/wagyu-sliced.jpg'),
    width: 1122,
    height: 1402,
    origin: 'photograph',
  },
  'wine-pour': {
    source: require('../../assets/photos/wine-pour.jpg'),
    width: 1312,
    height: 1199,
    origin: 'photograph',
  },
} as const satisfies Record<string, PhotoEntry>;

export type PhotoKey = keyof typeof photoRegistry;
