/**
 * CMS seed content.
 *
 * FACTS FROM THE BRIEF (isSample: false):
 *   - venue: Waterfall Wilds / Waterfall City, Midrand
 *   - reservations@maburestaurant.com
 *   - Meerlust Wine Pairing, 27 October 2026, 18:30–22:00, Waterfall Wilds, R900
 *   - the thirteen menu categories (§9)
 *   - brand copy from the supplied brand board ("A culinary journey rooted in
 *     culture, crafted for today", "Elegant • Savoir-faire fusion • Afro luxury")
 *
 * EVERYTHING ELSE IS SAMPLE (isSample: true) — dish names, descriptions,
 * prices, wines and their prices, opening hours, arrival notes, the other
 * events. The published menus could not be fetched from this environment,
 * and the brief (§28) says to use real menu content only as clearly labelled
 * seed data. The app shows a "Sample menu" note while any item is sample.
 * Replace these through Admin → Menu, or the CMS once connected.
 */
import type { Dish, MenuCollection, WineItem } from '../domain/menu/types';
import type { Experience } from '../domain/experiences/types';
import type { Reward, RewardRule, RewardTier } from '../domain/rewards/types';
import type { HomeContent, VenueContent } from './types';

const T = '2026-09-01T00:00:00+02:00';

export const SEED_VENUE: VenueContent = {
  id: 'venue',
  name: 'Mábu Restaurant',
  area: 'Waterfall Wilds, Midrand',
  addressLines: ['Waterfall Wilds', 'Waterfall City, Midrand', 'Gauteng, South Africa'],
  email: 'reservations@maburestaurant.com',
  phone: null,
  mapsQuery: 'Mábu Restaurant, Waterfall Wilds, Midrand',
  hours: [
    { day: 1, label: 'Monday', hours: null },
    { day: 2, label: 'Tuesday', hours: '12:00 – 22:30' },
    { day: 3, label: 'Wednesday', hours: '12:00 – 22:30' },
    { day: 4, label: 'Thursday', hours: '12:00 – 22:30' },
    { day: 5, label: 'Friday', hours: '12:00 – 23:00' },
    { day: 6, label: 'Saturday', hours: '12:00 – 23:00' },
    { day: 0, label: 'Sunday', hours: '12:00 – 17:00' },
  ],
  arrivalNotes: [
    'Secure parking is available at Waterfall Wilds.',
    'Step-free access from the entrance to the main dining room.',
    'Smart-elegant dress is appreciated.',
  ],
  dineplanUrl: 'https://www.dineplan.com/restaurant/mabu-restaurant',
  isSample: true,
  updatedAt: T,
};

export const SEED_HOME: HomeContent = {
  id: 'home',
  heroPhoto: 'signature-steak',
  heroTitle: 'African Luxury.\nRefined by Fire.',
  heroSubtitle: 'Elegant  •  Savoir-faire fusion  •  Afro luxury',
  essenceTitle: 'A culinary journey rooted in culture, crafted for today.',
  essenceBody:
    'MÁBU is a contemporary African luxury restaurant that brings together exceptional cuisine, cultured hospitality and unforgettable experiences in a sophisticated, modern setting.',
  stories: [
    {
      id: 'story-fire',
      eyebrow: 'Fire & Flavour',
      title: 'Where heritage meets the flame',
      body: 'Our signature cuts are aged, seasoned with African spice and finished over open fire — bold flavours, modern technique.',
      photo: 'dish-signature-mains',
    },
    {
      id: 'story-room',
      eyebrow: 'The Room',
      title: 'Timber, brass and stone',
      body: 'Beneath hand-crafted timber chandeliers, forest-green velvet and marble, every table is set for an occasion.',
      photo: 'dining-room',
    },
    {
      id: 'story-gather',
      eyebrow: 'Private Functions',
      title: 'Gather in grand style',
      body: 'Exclusive experiences and memorable occasions — from intimate celebrations to long-table feasts.',
      photo: 'private-dining',
    },
  ],
  highlightDishIds: ['sig-fillet', 'fish-kingklip', 'des-chocolate', 'start-prawns', 'sc-oxtail'],
  wineSpotlightId: 'wine-rubicon',
  voucherTitle: 'Give the gift of Mábu.',
  voucherBody: 'A digital voucher for an evening to remember — delivered beautifully, in moments.',
  updatedAt: T,
};

type DishSeed = Omit<
  Dish,
  'currency' | 'isSample' | 'updatedAt' | 'available' | 'allergens' | 'dietaryTags' | 'spiceLevel'
> &
  Partial<Pick<Dish, 'available' | 'allergens' | 'dietaryTags' | 'spiceLevel'>>;

const dish = (d: DishSeed): Dish => ({
  available: true,
  allergens: [],
  dietaryTags: [],
  spiceLevel: 0,
  ...d,
  currency: 'ZAR',
  isSample: true,
  updatedAt: T,
});

export const SEED_DISHES: Dish[] = [
  // Starters
  dish({
    id: 'start-prawns',
    name: 'Peri-Peri Tiger Prawns',
    description:
      'Flame-grilled tiger prawns, bird’s-eye chilli butter, charred lemon, micro coriander.',
    priceCents: 19500,
    category: 'starters',
    photo: 'dish-seafood',
    allergens: ['crustaceans', 'dairy'],
    spiceLevel: 2,
    signature: true,
    pairingIds: ['wine-mullineux-white', 'wine-graham-beck'],
  }),
  dish({
    id: 'start-tartare',
    name: 'Beef Tartare, Umami Dressing',
    description:
      'Hand-cut fillet, soy and sesame dressing, pickled shimeji, crisp cassava, cured yolk.',
    priceCents: 17500,
    category: 'starters',
    allergens: ['egg', 'soy', 'sesame'],
    chefSelected: true,
    pairingIds: ['wine-meerlust-pinot'],
  }),
  dish({
    id: 'start-bao',
    name: 'Chakalaka Pork Belly Bao',
    description: 'Twice-cooked pork belly, chakalaka glaze, pickled cucumber, steamed bao.',
    priceCents: 14500,
    category: 'starters',
    allergens: ['gluten', 'soy'],
    spiceLevel: 1,
  }),
  // Salads
  dish({
    id: 'salad-heirloom',
    name: 'Heirloom Tomato & Burrata',
    description:
      'Heirloom tomatoes, burrata, baobab vinaigrette, basil oil, toasted pumpkin seeds.',
    priceCents: 13500,
    category: 'salads',
    allergens: ['dairy'],
    dietaryTags: ['vegetarian'],
  }),
  dish({
    id: 'salad-duck',
    name: 'Smoked Duck & Citrus',
    description: 'Rooibos-smoked duck breast, orange, fennel, wild rocket, miso-honey dressing.',
    priceCents: 15500,
    category: 'salads',
    allergens: ['soy'],
  }),
  // Vegetarian
  dish({
    id: 'veg-risotto',
    name: 'Wild Mushroom & Sorghum Risotto',
    description: 'Creamy sorghum, roasted wild mushrooms, truffle, aged parmesan, crispy sage.',
    priceCents: 19500,
    category: 'vegetarian',
    allergens: ['dairy'],
    dietaryTags: ['vegetarian'],
  }),
  dish({
    id: 'veg-cauliflower',
    name: 'Fire-Roasted Cauliflower',
    description: 'Whole-roasted cauliflower, berbere spice, tahini, pomegranate, herb oil.',
    priceCents: 16500,
    category: 'vegetarian',
    allergens: ['sesame'],
    dietaryTags: ['vegetarian', 'vegan'],
    spiceLevel: 1,
  }),
  // Signature cuts
  dish({
    id: 'sig-fillet',
    name: 'The Mábu Fillet',
    description:
      'Aged beef fillet over open flame, charred tenderstem broccoli, heirloom carrots, truffle pomme purée, crispy leek.',
    priceCents: 42500,
    category: 'signature-cuts',
    photo: 'signature-steak',
    gallery: ['dish-signature-mains', 'dining-room'],
    allergens: ['dairy'],
    signature: true,
    chefSelected: true,
    provenance: 'Grass-fed, free-range beef, dry-aged in house for 28 days.',
    preparation: 'Seared over hardwood fire, rested, finished with bone-marrow butter.',
    pairingIds: ['wine-rubicon', 'wine-kanonkop'],
    modifiers: [
      {
        id: 'doneness',
        name: 'How would you like it?',
        required: true,
        maxSelections: 1,
        options: [
          { id: 'rare', name: 'Rare', priceDeltaCents: 0 },
          { id: 'medium-rare', name: 'Medium rare', priceDeltaCents: 0 },
          { id: 'medium', name: 'Medium', priceDeltaCents: 0 },
        ],
      },
      {
        id: 'sauce',
        name: 'Choose a sauce',
        required: false,
        maxSelections: 1,
        options: [
          { id: 'peppercorn', name: 'Green peppercorn', priceDeltaCents: 0 },
          { id: 'bordelaise', name: 'Bone-marrow bordelaise', priceDeltaCents: 3500 },
        ],
      },
    ],
  }),
  dish({
    id: 'sig-tomahawk',
    name: 'Tomahawk for Two',
    description: '1.2kg tomahawk, smoked salt, chimichurri, fire-roasted bone marrow, two sides.',
    priceCents: 129500,
    category: 'signature-cuts',
    photo: 'dish-signature-mains',
    allergens: [],
    signature: true,
    pairingIds: ['wine-rubicon'],
  }),
  dish({
    id: 'sig-wagyu',
    name: 'Wagyu Rump Cap, Yakiniku Glaze',
    description: 'Wagyu picanha, yakiniku glaze, pickled daikon, spring onion.',
    priceCents: 59500,
    category: 'signature-cuts',
    allergens: ['soy', 'sesame'],
    chefSelected: true,
    pairingIds: ['wine-kanonkop'],
  }),
  // Classic steaks
  dish({
    id: 'steak-sirloin',
    name: 'Sirloin 300g',
    description: 'Aged sirloin, hand-cut chips, café de Paris butter.',
    priceCents: 31500,
    category: 'classic-steaks',
    allergens: ['dairy'],
    pairingIds: ['wine-kanonkop'],
  }),
  dish({
    id: 'steak-ribeye',
    name: 'Rib-Eye 400g',
    description: 'Well-marbled rib-eye, confit garlic, roasted marrow bone.',
    priceCents: 38500,
    category: 'classic-steaks',
    allergens: [],
    pairingIds: ['wine-rubicon'],
  }),
  // Poultry & game
  dish({
    id: 'pg-springbok',
    name: 'Springbok Loin',
    description: 'Seared springbok, amarula jus, butternut purée, roasted beetroot.',
    priceCents: 34500,
    category: 'poultry-game',
    allergens: ['dairy'],
    signature: true,
    provenance: 'Karoo-sourced springbok.',
    pairingIds: ['wine-meerlust-pinot'],
  }),
  dish({
    id: 'pg-chicken',
    name: 'Flame-Grilled Baby Chicken',
    description: 'Deboned baby chicken, lemon-thyme or peri-peri basting, charred corn.',
    priceCents: 22500,
    category: 'poultry-game',
    allergens: ['dairy'],
    spiceLevel: 1,
  }),
  // Fish
  dish({
    id: 'fish-kingklip',
    name: 'Kingklip, Black Rice & Mussels',
    description:
      'Pan-roasted kingklip, squid-ink black rice, West Coast mussels, salmon roe, sea herbs.',
    priceCents: 32500,
    category: 'fish',
    photo: 'dish-seafood',
    allergens: ['fish', 'molluscs'],
    signature: true,
    pairingIds: ['wine-hamilton-russell', 'wine-mullineux-white'],
  }),
  dish({
    id: 'fish-salmon',
    name: 'Miso-Glazed Salmon',
    description: 'Norwegian salmon, white miso glaze, bok choy, ginger dashi.',
    priceCents: 29500,
    category: 'fish',
    allergens: ['fish', 'soy'],
    pairingIds: ['wine-hamilton-russell'],
  }),
  // Pasta
  dish({
    id: 'pasta-oxtail',
    name: 'Oxtail Pappardelle',
    description: 'Hand-rolled pappardelle, slow-braised oxtail ragù, gremolata, parmesan.',
    priceCents: 21500,
    category: 'pasta',
    allergens: ['gluten', 'egg', 'dairy'],
  }),
  dish({
    id: 'pasta-prawn',
    name: 'Prawn Linguine, Chilli & Lime',
    description: 'Linguine, prawns, chilli, lime leaf, coconut cream.',
    priceCents: 23500,
    category: 'pasta',
    allergens: ['gluten', 'crustaceans'],
    spiceLevel: 2,
  }),
  // Slow cooked
  dish({
    id: 'sc-oxtail',
    name: 'Braised Oxtail',
    description: 'Eight-hour red-wine oxtail, samp and beans, roasted root vegetables.',
    priceCents: 29500,
    category: 'slow-cooked',
    allergens: [],
    signature: true,
    pairingIds: ['wine-kanonkop'],
  }),
  dish({
    id: 'sc-lamb',
    name: 'Karoo Lamb Shank',
    description: 'Slow-cooked lamb shank, rosemary jus, creamed pap, glazed carrots.',
    priceCents: 32500,
    category: 'slow-cooked',
    allergens: ['dairy'],
    available: false,
  }),
  // Sides
  dish({
    id: 'side-pomme',
    name: 'Truffle Pomme Purée',
    description: 'Silky potato purée, truffle.',
    priceCents: 6500,
    category: 'sides',
    allergens: ['dairy'],
    dietaryTags: ['vegetarian'],
  }),
  dish({
    id: 'side-broccoli',
    name: 'Charred Tenderstem',
    description: 'Tenderstem broccoli, chilli, toasted almonds.',
    priceCents: 6500,
    category: 'sides',
    allergens: ['nuts'],
    dietaryTags: ['vegetarian', 'vegan'],
  }),
  dish({
    id: 'side-chips',
    name: 'Hand-Cut Chips',
    description: 'Triple-cooked, smoked salt.',
    priceCents: 5500,
    category: 'sides',
    dietaryTags: ['vegetarian', 'vegan'],
  }),
  // Sauces
  dish({
    id: 'sauce-peppercorn',
    name: 'Green Peppercorn',
    description: 'Brandy, cream, green peppercorn.',
    priceCents: 4500,
    category: 'sauces',
    allergens: ['dairy'],
    dietaryTags: ['vegetarian'],
  }),
  dish({
    id: 'sauce-bordelaise',
    name: 'Bone-Marrow Bordelaise',
    description: 'Red wine, shallot, roasted marrow.',
    priceCents: 5500,
    category: 'sauces',
  }),
  dish({
    id: 'sauce-chimichurri',
    name: 'Mábu Chimichurri',
    description: 'Herbs, chilli, garlic, olive oil.',
    priceCents: 4000,
    category: 'sauces',
    dietaryTags: ['vegetarian', 'vegan'],
    spiceLevel: 1,
  }),
  // Desserts
  dish({
    id: 'des-chocolate',
    name: 'Dark Chocolate & Coconut',
    description: 'Dark chocolate délice, coconut sphere, salted caramel, cocoa soil.',
    priceCents: 12500,
    category: 'desserts',
    photo: 'dish-desserts',
    allergens: ['dairy', 'gluten', 'egg'],
    dietaryTags: ['vegetarian'],
    signature: true,
    pairingIds: ['wine-vin-de-constance'],
  }),
  dish({
    id: 'des-malva',
    name: 'Rooibos Malva Pudding',
    description: 'Warm malva, rooibos custard, amarula ice cream.',
    priceCents: 10500,
    category: 'desserts',
    allergens: ['dairy', 'gluten', 'egg'],
    dietaryTags: ['vegetarian'],
    pairingIds: ['wine-vin-de-constance'],
  }),
  dish({
    id: 'des-yuzu',
    name: 'Yuzu & Baobab Tart',
    description: 'Yuzu curd, baobab meringue, sesame tuile.',
    priceCents: 11500,
    category: 'desserts',
    allergens: ['dairy', 'gluten', 'egg', 'sesame'],
    dietaryTags: ['vegetarian'],
  }),
];

const wine = (
  w: Omit<WineItem, 'isSample' | 'updatedAt' | 'available'> & { available?: boolean },
): WineItem => ({
  available: true,
  ...w,
  isSample: true,
  updatedAt: T,
});

export const SEED_WINES: WineItem[] = [
  wine({
    id: 'wine-graham-beck',
    name: 'Brut NV',
    producer: 'Graham Beck',
    region: 'Robertson',
    varietal: 'Chardonnay, Pinot Noir',
    style: 'sparkling',
    glassPriceCents: 9500,
    bottlePriceCents: 48500,
    tastingNotes: 'Fine persistent bubbles; green apple, citrus and a hint of brioche.',
    pairingTags: ['seafood', 'celebration', 'starters'],
  }),
  wine({
    id: 'wine-hamilton-russell',
    name: 'Chardonnay',
    producer: 'Hamilton Russell Vineyards',
    region: 'Hemel-en-Aarde Valley',
    varietal: 'Chardonnay',
    style: 'white',
    bottlePriceCents: 145000,
    tastingNotes: 'Taut and mineral; lemon curd, hazelnut and a long saline finish.',
    pairingTags: ['fish', 'poultry'],
  }),
  wine({
    id: 'wine-mullineux-white',
    name: 'Old Vines White',
    producer: 'Mullineux',
    region: 'Swartland',
    varietal: 'Chenin Blanc blend',
    style: 'white',
    glassPriceCents: 16500,
    bottlePriceCents: 79500,
    tastingNotes: 'Textured stone fruit, orange blossom and wet stone.',
    pairingTags: ['seafood', 'spice', 'vegetarian'],
  }),
  wine({
    id: 'wine-meerlust-pinot',
    name: 'Pinot Noir',
    producer: 'Meerlust',
    region: 'Stellenbosch',
    varietal: 'Pinot Noir',
    style: 'red',
    glassPriceCents: 14500,
    bottlePriceCents: 69500,
    tastingNotes: 'Red cherry, forest floor and gentle spice; silky tannins.',
    pairingTags: ['game', 'duck', 'tartare'],
  }),
  wine({
    id: 'wine-rubicon',
    name: 'Rubicon',
    producer: 'Meerlust',
    region: 'Stellenbosch',
    varietal: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    style: 'red',
    bottlePriceCents: 125000,
    tastingNotes: 'Cassis, cedar and cigar box; structured, elegant and long-lived.',
    pairingTags: ['beef', 'signature cuts', 'fire'],
  }),
  wine({
    id: 'wine-kanonkop',
    name: 'Pinotage',
    producer: 'Kanonkop',
    region: 'Stellenbosch',
    varietal: 'Pinotage',
    style: 'red',
    glassPriceCents: 18500,
    bottlePriceCents: 89500,
    tastingNotes: 'Plum, mulberry and smoke; bold with a fine tannic grip.',
    pairingTags: ['beef', 'oxtail', 'braai'],
  }),
  wine({
    id: 'wine-delaire-rose',
    name: 'Cabernet Franc Rosé',
    producer: 'Delaire Graff',
    region: 'Stellenbosch',
    varietal: 'Cabernet Franc',
    style: 'rose',
    glassPriceCents: 11500,
    bottlePriceCents: 52500,
    tastingNotes: 'Strawberry, rose petal and crisp acidity.',
    pairingTags: ['salads', 'lunch'],
  }),
  wine({
    id: 'wine-vin-de-constance',
    name: 'Vin de Constance',
    producer: 'Klein Constantia',
    region: 'Constantia',
    varietal: 'Muscat de Frontignan',
    style: 'dessert-fortified',
    glassPriceCents: 26500,
    bottlePriceCents: 195000,
    tastingNotes: 'Apricot, honeyed citrus and spice; luscious yet fresh.',
    pairingTags: ['dessert', 'chocolate', 'cheese'],
  }),
];

export const SEED_COLLECTIONS: MenuCollection[] = [
  {
    id: 'col-fire',
    name: 'Refined by Fire',
    description: 'Our signature cuts, seasoned with heritage and finished over the flame.',
    photo: 'signature-steak',
    itemIds: ['sig-fillet', 'sig-tomahawk', 'sig-wagyu', 'steak-ribeye'],
  },
  {
    id: 'col-ocean',
    name: 'Ocean to Our Table',
    description: 'Refined and fresh — from the West Coast to your plate.',
    photo: 'dish-seafood',
    itemIds: ['start-prawns', 'fish-kingklip', 'fish-salmon', 'pasta-prawn'],
  },
  {
    id: 'col-sweet',
    name: 'A Sweet Taste of the Extraordinary',
    description: 'Desserts to linger over, with the perfect glass.',
    photo: 'dish-desserts',
    itemIds: ['des-chocolate', 'des-malva', 'des-yuzu'],
  },
];

/** The brief's one confirmed event is real; the rest are sample and flagged. */
export const SEED_EXPERIENCES: Experience[] = [
  {
    id: 'evt-meerlust-2026-10-27',
    title: 'Meerlust Wine Pairing',
    subtitle: 'An evening with one of Stellenbosch’s great estates',
    kind: 'wine-pairing',
    startsAt: '2026-10-27T18:30:00+02:00',
    endsAt: '2026-10-27T22:00:00+02:00',
    room: 'Mábu Restaurant, Waterfall Wilds',
    priceCents: 90000,
    capacity: 48,
    seatsBooked: 31,
    maxSeatsPerBooking: 6,
    waitlistEnabled: true,
    description:
      'A curated pairing dinner showcasing the Meerlust estate alongside a menu composed by our kitchen for the evening. Each course is matched to a Meerlust wine, introduced at the table.',
    menuTeaser: [
      'Amuse-bouche',
      'Beef tartare, umami dressing',
      'Springbok loin, amarula jus',
      'The Mábu fillet',
      'Dark chocolate & coconut',
    ],
    winePartner: 'Meerlust Estate',
    dressCode: 'Smart elegant',
    ageRule: 'Guests 18 and over',
    heroPhoto: 'dish-wines',
    bookingRequired: true,
    published: true,
    isSample: false,
    updatedAt: T,
  },
  {
    id: 'evt-chefs-table-2026-11',
    title: 'Chef’s Table: Fire & Spice',
    subtitle: 'Seven courses from the open flame',
    kind: 'chef-evening',
    startsAt: '2026-11-20T19:00:00+02:00',
    endsAt: '2026-11-20T22:30:00+02:00',
    room: 'The Chef’s Table',
    priceCents: 125000,
    capacity: 14,
    seatsBooked: 14,
    maxSeatsPerBooking: 4,
    waitlistEnabled: true,
    description:
      'An intimate seven-course journey at the pass, cooked over fire and introduced by our chef. Limited to fourteen guests.',
    menuTeaser: ['Seven courses', 'Optional wine pairing'],
    dressCode: 'Smart elegant',
    ageRule: 'Guests 18 and over',
    heroPhoto: 'chandeliers',
    bookingRequired: true,
    published: true,
    isSample: true,
    updatedAt: T,
  },
  {
    id: 'evt-festive-2026-12',
    title: 'Festive Tasting Menu',
    subtitle: 'Celebrate the season, the Mábu way',
    kind: 'tasting-menu',
    startsAt: '2026-12-12T18:30:00+02:00',
    endsAt: '2026-12-12T22:30:00+02:00',
    room: 'Main Dining Room',
    priceCents: 95000,
    capacity: 80,
    seatsBooked: 12,
    maxSeatsPerBooking: 8,
    waitlistEnabled: false,
    description:
      'A festive tasting menu with MCC on arrival, for the season of long tables and good company.',
    dressCode: 'Festive elegant',
    heroPhoto: 'private-dining',
    bookingRequired: true,
    published: true,
    isSample: true,
    updatedAt: T,
  },
];

/** §34: "Member / Signature / Privé or future names supplied by MÁBU". */
export const SEED_TIERS: RewardTier[] = [
  {
    id: 'member',
    name: 'Member',
    minLifetimePoints: 0,
    order: 1,
    benefits: ['Points on every visit and event', 'Birthday recognition', 'Member news first'],
  },
  {
    id: 'signature',
    name: 'Signature',
    minLifetimePoints: 1500,
    order: 2,
    benefits: ['Priority booking window for events', 'Welcome glass of MCC', 'All Member benefits'],
  },
  {
    id: 'prive',
    name: 'Privé',
    minLifetimePoints: 4000,
    order: 3,
    benefits: [
      'Invitation-only chef evenings',
      'Preferred table on request',
      'All Signature benefits',
    ],
  },
];

export const SEED_RULES: RewardRule[] = [
  {
    id: 'rule-visit',
    name: 'Dining visit',
    trigger: 'completed_visit',
    points: 250,
    active: true,
    updatedAt: T,
  },
  {
    id: 'rule-event',
    name: 'Event attended',
    trigger: 'event_attendance',
    points: 400,
    active: true,
    updatedAt: T,
  },
  {
    id: 'rule-voucher',
    name: 'Gift voucher purchase',
    trigger: 'purchase',
    points: 0,
    pointsPer100Rand: 10,
    active: true,
    updatedAt: T,
  },
  {
    id: 'rule-referral',
    name: 'Friend’s first visit',
    trigger: 'referral',
    points: 300,
    active: true,
    updatedAt: T,
  },
  {
    id: 'rule-birthday',
    name: 'Birthday gift',
    trigger: 'birthday',
    points: 200,
    active: true,
    updatedAt: T,
  },
  {
    id: 'rule-campaign',
    name: 'Campaign bonus',
    trigger: 'campaign',
    points: 100,
    active: false,
    updatedAt: T,
  },
];

export const SEED_REWARDS: Reward[] = [
  {
    id: 'rw-amuse',
    name: 'Chef’s Amuse-Bouche for the Table',
    description: 'A seasonal amuse-bouche from the kitchen, for everyone at your table.',
    terms: 'One per booking. Present the code on arrival.',
    kind: 'gift',
    pointsCost: 500,
    redemptionValidDays: 90,
    active: true,
    photo: 'table-setting',
  },
  {
    id: 'rw-pairing',
    name: 'Sommelier’s Pairing Upgrade for Two',
    description: 'Upgrade to the sommelier’s wine pairing with your mains, for two guests.',
    terms: 'Guests 18 and over. One per booking.',
    kind: 'pairing-upgrade',
    pointsCost: 1200,
    redemptionValidDays: 90,
    active: true,
    photo: 'dish-wines',
  },
  {
    id: 'rw-priority',
    name: 'Priority Event Booking',
    description: 'Book headline events 48 hours before general release.',
    terms: 'Valid for one event booking.',
    kind: 'priority-booking',
    pointsCost: 800,
    tierIds: ['signature', 'prive'],
    redemptionValidDays: 180,
    active: true,
    photo: 'chandeliers',
  },
  {
    id: 'rw-spice',
    name: 'Mábu Spice Collection',
    description: 'Our house spice blends, beautifully boxed to take home.',
    terms: 'Collect at the restaurant. While stocks last.',
    kind: 'gift',
    pointsCost: 1500,
    redemptionValidDays: 90,
    active: true,
    photo: 'texture-pattern',
  },
  {
    id: 'rw-chefs-table',
    name: 'Invitation: Privé Chef’s Evening',
    description: 'Two seats at an invitation-only evening at the chef’s table.',
    terms: 'Privé members. Subject to availability of scheduled evenings.',
    kind: 'invitation',
    pointsCost: 3000,
    tierIds: ['prive'],
    redemptionValidDays: 365,
    active: true,
    photo: 'bar-lounge',
  },
];
