import { flagsFromEnv } from '@/domain/flags';

/**
 * Expo inlines `process.env.EXPO_PUBLIC_*` only where it is written out in
 * full, so every variable is listed by name here rather than read dynamically.
 */
const env: Record<string, string | undefined> = {
  EXPO_PUBLIC_MABU_BOOKING_ENABLED: process.env.EXPO_PUBLIC_MABU_BOOKING_ENABLED,
  EXPO_PUBLIC_MABU_BOOKING_PROVIDER: process.env.EXPO_PUBLIC_MABU_BOOKING_PROVIDER,
  EXPO_PUBLIC_MABU_WAITLIST_ENABLED: process.env.EXPO_PUBLIC_MABU_WAITLIST_ENABLED,
  EXPO_PUBLIC_MABU_BOOKING_DEPOSIT_ENABLED: process.env.EXPO_PUBLIC_MABU_BOOKING_DEPOSIT_ENABLED,
  EXPO_PUBLIC_MABU_REWARDS_ENABLED: process.env.EXPO_PUBLIC_MABU_REWARDS_ENABLED,
  EXPO_PUBLIC_MABU_REWARDS_EARNING_ENABLED: process.env.EXPO_PUBLIC_MABU_REWARDS_EARNING_ENABLED,
  EXPO_PUBLIC_MABU_REWARDS_REDEMPTION_ENABLED:
    process.env.EXPO_PUBLIC_MABU_REWARDS_REDEMPTION_ENABLED,
  EXPO_PUBLIC_MABU_NOTIFICATIONS_ENABLED: process.env.EXPO_PUBLIC_MABU_NOTIFICATIONS_ENABLED,
  EXPO_PUBLIC_MABU_PUSH_ENABLED: process.env.EXPO_PUBLIC_MABU_PUSH_ENABLED,
  EXPO_PUBLIC_MABU_EMAIL_ENABLED: process.env.EXPO_PUBLIC_MABU_EMAIL_ENABLED,
  EXPO_PUBLIC_MABU_SMS_ENABLED: process.env.EXPO_PUBLIC_MABU_SMS_ENABLED,
  EXPO_PUBLIC_MABU_WHATSAPP_ENABLED: process.env.EXPO_PUBLIC_MABU_WHATSAPP_ENABLED,
  EXPO_PUBLIC_MABU_MARKETING_NOTIFICATIONS_ENABLED:
    process.env.EXPO_PUBLIC_MABU_MARKETING_NOTIFICATIONS_ENABLED,
  EXPO_PUBLIC_MABU_VOUCHERS_ENABLED: process.env.EXPO_PUBLIC_MABU_VOUCHERS_ENABLED,
  EXPO_PUBLIC_MABU_EVENTS_ENABLED: process.env.EXPO_PUBLIC_MABU_EVENTS_ENABLED,
  EXPO_PUBLIC_MABU_DIRECT_ORDERING_ENABLED: process.env.EXPO_PUBLIC_MABU_DIRECT_ORDERING_ENABLED,
  EXPO_PUBLIC_UBER_EATS_ENABLED: process.env.EXPO_PUBLIC_UBER_EATS_ENABLED,
  EXPO_PUBLIC_MR_D_ENABLED: process.env.EXPO_PUBLIC_MR_D_ENABLED,
};

export const config = {
  useMockApi: (process.env.EXPO_PUBLIC_USE_MOCK_API ?? '1') !== '0',
  apiBaseUrl: process.env.EXPO_PUBLIC_API_BASE_URL ?? 'https://api.maburestaurant.com',
  /** Only used by the in-app mock back end; a live server reads its own. */
  mockFlags: flagsFromEnv(env),
} as const;
