import type { Product } from '@bbq/types';

/**
 * The catalogue, ported from the reference build and extended since. Prices
 * are demo values pending CLAUDE.md section 8; the allergen and energy figures
 * are indicative pending the franchisor nutritional analysis.
 *
 * PHOTOGRAPHY. Every product has its own master. For a while the eight items
 * added past the original sixteen borrowed the image that most honestly
 * depicted them; each has since been shot and wired to its own. A test holds
 * the invariant, so a new item added without a photograph fails rather than
 * quietly wearing another dish's.
 *
 * imageKey is the supplied master's file name, which does not always match the
 * slug — the masters were named before the slugs were settled, and masters are
 * never renamed or edited.
 */
export const PRODUCTS: readonly Product[] = [
  {
    id: 'P-golden-original',
    slug: 'golden-original',
    name: 'Golden Original Chicken',
    category: 'Chicken',
    priceCents: 18_900,
    heat: 1,
    sauce: 'No sauce',
    tag: 'Best seller',
    description:
      'The original recipe. Twice fried in olive oil, seasoned and served bare so the crunch does the talking.',
    imageKey: 'golden-original',
    nutrition: { allergens: 'Wheat, soya', kilojoules: 1_180 },
    soldOut: false,
  },
  {
    id: 'P-honey-garlic',
    slug: 'honey-garlic',
    name: 'Honey Garlic Chicken',
    category: 'Chicken',
    priceCents: 20_900,
    heat: 2,
    sauce: 'Honey garlic',
    tag: 'Best seller',
    description:
      'Sticky honey and roasted garlic, tossed to order and finished with sesame and spring onion.',
    imageKey: 'honey-garlic',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_290 },
    soldOut: false,
  },
  {
    id: 'P-soy-garlic',
    slug: 'soy-garlic',
    name: 'Soy Garlic Chicken',
    category: 'Chicken',
    priceCents: 20_900,
    heat: 2,
    sauce: 'Soy garlic',
    description:
      'Deep soy glaze with slow garlic. The most ordered flavour in Korea, and the easiest place to start.',
    imageKey: 'soy-garlic',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_265 },
    soldOut: false,
  },
  {
    id: 'P-secret-sauce',
    slug: 'secret-sauce',
    name: 'Secret Sauce Chicken',
    category: 'Chicken',
    priceCents: 21_500,
    heat: 4,
    sauce: 'Secret sauce',
    tag: 'New',
    description: 'Sweet at the front, hot at the back. The house sauce that people come back for.',
    imageKey: 'secret-sauce',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_310 },
    soldOut: false,
  },
  {
    id: 'P-hot-spicy',
    slug: 'hot-spicy',
    name: 'Hot Spicy Chicken',
    category: 'Chicken',
    priceCents: 21_500,
    heat: 5,
    sauce: 'Hot spicy',
    description:
      'Gochujang heat with fresh chilli, cut with sesame. Order water. You will need it.',
    imageKey: 'hot-spicy',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_305 },
    soldOut: false,
  },
  {
    id: 'P-cheesling',
    slug: 'cheesling',
    name: 'Cheesling Chicken',
    category: 'Chicken',
    priceCents: 21_900,
    heat: 1,
    sauce: 'Cheese dust',
    description:
      'Golden Original under a heavy snow of savoury cheese seasoning. A crowd favourite with kids.',
    imageKey: 'cheesling',
    nutrition: { allergens: 'Wheat, soya, milk', kilojoules: 1_360 },
    soldOut: false,
  },
  {
    id: 'P-half-half',
    slug: 'half-half',
    name: 'Half and Half Chicken',
    category: 'Chicken',
    priceCents: 22_900,
    heat: 3,
    sauce: 'Pick two',
    tag: 'Table share',
    description:
      'One bird, two flavours. Choose any two sauces and settle the argument at the table.',
    imageKey: 'half-and-half',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_290 },
    soldOut: false,
  },
  {
    id: 'P-golden-wings',
    slug: 'golden-wings',
    name: 'Golden Original Wings',
    category: 'Wings',
    priceCents: 17_900,
    heat: 1,
    sauce: 'No sauce',
    tag: 'Best seller',
    description: 'Whole wings, twice fried, salted while hot. Add any sauce on the side.',
    imageKey: 'golden-original-wings',
    nutrition: { allergens: 'Wheat, soya', kilojoules: 1_140 },
    soldOut: false,
  },
  {
    id: 'P-boneless',
    slug: 'boneless',
    name: 'Boneless Chicken',
    category: 'Wings',
    priceCents: 16_900,
    heat: 2,
    sauce: 'Choose sauce',
    description: 'Breast pieces in the signature crumb. All of the crunch, none of the bones.',
    imageKey: 'boneless',
    nutrition: { allergens: 'Wheat, soya', kilojoules: 1_095 },
    soldOut: false,
  },
  {
    id: 'P-chicken-rice',
    slug: 'chicken-rice',
    name: 'Chicken and Rice Meal',
    category: 'Meals',
    priceCents: 12_900,
    heat: 2,
    sauce: 'Choose sauce',
    tag: 'Meal deal',
    description: 'Three pieces, steamed rice, house slaw, dipping sauce and a drink.',
    imageKey: 'chicken-rice-meal',
    nutrition: { allergens: 'Wheat, soya, egg', kilojoules: 2_240 },
    soldOut: false,
  },
  {
    id: 'P-chicken-burger',
    slug: 'chicken-burger',
    name: 'Chicken Burger',
    category: 'Meals',
    priceCents: 9_900,
    heat: 3,
    sauce: 'Secret sauce',
    description:
      'Crunchy fillet, glazed and stacked with lettuce, red onion, pickles and house mayo. Served with fries and a drink.',
    imageKey: 'chicken-burger',
    nutrition: { allergens: 'Wheat, soya, egg, sesame', kilojoules: 2_380 },
    soldOut: false,
  },
  {
    id: 'P-korean-rice-bowl',
    slug: 'korean-rice-bowl',
    name: 'Korean Rice Bowl',
    category: 'Meals',
    priceCents: 11_900,
    heat: 3,
    sauce: 'Sweet and spicy',
    tag: 'New',
    description:
      'Boneless chicken over rice with kimchi, cucumber, carrot, seaweed and a creamy drizzle.',
    imageKey: 'korean-rice-bowl',
    nutrition: { allergens: 'Wheat, soya, sesame, fish', kilojoules: 2_150 },
    soldOut: false,
  },
  {
    id: 'P-french-fries',
    slug: 'french-fries',
    name: 'French Fries',
    category: 'Sides',
    priceCents: 3_900,
    heat: 0,
    sauce: 'Salted',
    description: 'Crispy outside, fluffy inside. Seasoned the moment they leave the fryer.',
    imageKey: 'french-fries',
    nutrition: { allergens: 'None declared', kilojoules: 980 },
    soldOut: false,
  },
  {
    id: 'P-cheesling-fries',
    slug: 'cheesling-fries',
    name: 'Cheesling Fries',
    category: 'Sides',
    priceCents: 5_900,
    heat: 1,
    sauce: 'Cheese',
    description: 'Fries loaded with cheese sauce, jalapeno and crisp bacon bits.',
    imageKey: 'cheesling-fries',
    nutrition: { allergens: 'Milk, wheat', kilojoules: 1_520 },
    soldOut: false,
  },
  {
    id: 'P-ddeok-bokki',
    slug: 'ddeok-bokki',
    name: 'Ddeok-Bokki',
    category: 'Sides',
    priceCents: 6_900,
    heat: 4,
    sauce: 'Gochujang',
    description: 'Korean rice cakes in a bold gochujang sauce. Spicy, chewy, hard to share.',
    imageKey: 'ddeok-bokki',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_180 },
    soldOut: false,
  },
  {
    id: 'P-rose-ddeok-bokki',
    slug: 'rose-ddeok-bokki',
    name: 'Rose Ddeok-Bokki',
    category: 'Sides',
    priceCents: 7_900,
    heat: 2,
    sauce: 'Rose',
    description: 'Rice cakes in creamy rose sauce with mozzarella. The gentler way in.',
    imageKey: 'rose-ddeok-bokki',
    nutrition: { allergens: 'Milk, wheat, soya', kilojoules: 1_420 },
    soldOut: false,
  },
  {
    id: 'P-soy-garlic-wings',
    slug: 'soy-garlic-wings',
    name: 'Soy Garlic Wings',
    category: 'Wings',
    priceCents: 19_900,
    heat: 2,
    sauce: 'Soy garlic',
    description:
      'Whole wings tossed in the deep soy glaze after frying, so the crust holds under the sauce.',
    imageKey: 'soy-garlic-wings',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_210 },
    soldOut: false,
  },
  {
    id: 'P-honey-garlic-wings',
    slug: 'honey-garlic-wings',
    name: 'Honey Garlic Wings',
    category: 'Wings',
    priceCents: 19_900,
    heat: 2,
    sauce: 'Honey garlic',
    tag: 'New',
    description:
      'Sticky honey and roasted garlic on whole wings, finished with sesame and spring onion.',
    imageKey: 'honey-garlic-wings',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_240 },
    soldOut: false,
  },
  {
    id: 'P-hot-spicy-wings',
    slug: 'hot-spicy-wings',
    name: 'Hot Spicy Wings',
    category: 'Wings',
    priceCents: 19_900,
    heat: 5,
    sauce: 'Hot spicy',
    description:
      'Gochujang and fresh chilli on whole wings, cut with sesame. The hottest thing on the menu.',
    imageKey: 'hot-spicy-wings',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_255 },
    soldOut: false,
  },
  {
    id: 'P-secret-sauce-boneless',
    slug: 'secret-sauce-boneless',
    name: 'Secret Sauce Boneless',
    category: 'Wings',
    priceCents: 18_900,
    heat: 4,
    sauce: 'Secret sauce',
    description:
      'Breast pieces in the house sauce. Sweet at the front, hot at the back, and no bones to work around.',
    imageKey: 'secret-sauce-boneless',
    nutrition: { allergens: 'Wheat, soya, sesame', kilojoules: 1_150 },
    soldOut: false,
  },
  {
    id: 'P-wings-rice-meal',
    slug: 'wings-rice-meal',
    name: 'Wings and Rice Meal',
    category: 'Meals',
    priceCents: 13_900,
    heat: 2,
    sauce: 'Choose sauce',
    tag: 'Meal deal',
    description: 'Five wings, steamed rice, house slaw, dipping sauce and a drink.',
    imageKey: 'wings-rice-meal',
    nutrition: { allergens: 'Wheat, soya, egg', kilojoules: 2_180 },
    soldOut: false,
  },
  {
    id: 'P-cheesling-burger',
    slug: 'cheesling-burger',
    name: 'Cheesling Burger',
    category: 'Meals',
    priceCents: 10_900,
    heat: 1,
    sauce: 'Cheese dust',
    description:
      'The fillet under a heavy snow of cheese seasoning, stacked with lettuce and pickles. Fries and a drink included.',
    imageKey: 'cheesling-burger',
    nutrition: { allergens: 'Wheat, soya, egg, milk', kilojoules: 2_460 },
    soldOut: false,
  },
  {
    id: 'P-sweet-potato-fries',
    slug: 'sweet-potato-fries',
    name: 'Sweet Potato Fries',
    category: 'Sides',
    priceCents: 4_900,
    heat: 0,
    sauce: 'Salted',
    description: 'Cut thick and fried twice, so they stay crisp long enough to share.',
    imageKey: 'sweet-potato-fries',
    nutrition: { allergens: 'None declared', kilojoules: 1_040 },
    soldOut: false,
  },
  {
    id: 'P-cheese-ddeok-bokki',
    slug: 'cheese-ddeok-bokki',
    name: 'Cheese Ddeok-Bokki',
    category: 'Sides',
    priceCents: 7_900,
    heat: 3,
    sauce: 'Gochujang',
    description: 'Rice cakes in gochujang under a lid of melted mozzarella.',
    imageKey: 'cheese-ddeok-bokki',
    nutrition: { allergens: 'Milk, wheat, soya, sesame', kilojoules: 1_510 },
    soldOut: false,
  },
];